// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjpfmhscjftbqhdjkhnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcGZtaHNjamZ0YnFoZGpraG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjM2OTMsImV4cCI6MjA2MzAzOTY5M30.OsiPul26l-71Ufy7YO4cojQF0-csUVqfmblpmgZNkjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);